version: '3.8'

services:
  api:
    image: news-service
    container_name: api-container
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/news-db
      - NODE_ENV=production

  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

volumes:
  mongodb_data: